p 'CATEGORIA DE ACADEMIAS INICIO'

AcademyCategory.find_or_create_by(name: 'Technology')
AcademyCategory.find_or_create_by(name: 'Finance')
AcademyCategory.find_or_create_by(name: 'Languages')
AcademyCategory.find_or_create_by(name: 'Business')
AcademyCategory.find_or_create_by(name: 'My Company')
AcademyCategory.find_or_create_by(name: 'Health and Sports')
AcademyCategory.find_or_create_by(name: 'Finance and Investments')
AcademyCategory.find_or_create_by(name: 'Design')
AcademyCategory.find_or_create_by(name: 'Relationships')
AcademyCategory.find_or_create_by(name: 'Business and Career')
AcademyCategory.find_or_create_by(name: 'Espirituality')
AcademyCategory.find_or_create_by(name: 'Sexuality')
AcademyCategory.find_or_create_by(name: 'Entertaiment')
AcademyCategory.find_or_create_by(name: 'Culinary and Gastronomy')
AcademyCategory.find_or_create_by(name: 'Law')
AcademyCategory.find_or_create_by(name: 'Apps and Software')
AcademyCategory.find_or_create_by(name: 'Literature')
AcademyCategory.find_or_create_by(name: 'Home and Construction')
AcademyCategory.find_or_create_by(name: 'Personal development')
AcademyCategory.find_or_create_by(name: 'Fashion and Beauty')
AcademyCategory.find_or_create_by(name: 'Animals and plants')
AcademyCategory.find_or_create_by(name: 'Educational')
AcademyCategory.find_or_create_by(name: 'Hobbies')
AcademyCategory.find_or_create_by(name: 'Internet')
AcademyCategory.find_or_create_by(name: 'Ecology and Environment')
AcademyCategory.find_or_create_by(name: 'Art and music')
AcademyCategory.find_or_create_by(name: 'Information Technology')
AcademyCategory.find_or_create_by(name: 'Others')
AcademyCategory.find_or_create_by(name: 'Digital Entrepreneurship')

p 'CATEGORIA DE ACADEMIAS FINALIZADO'
