
services:
  api:
    build: 
      context: .
      args:
        RUBY_VERSION: '3.3.6'
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db:5432/iswo_academy_production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/rails
    command: "bundle exec rails server -p 3001 -b 0.0.0.0"
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=iswo_academy_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: