services:
  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
      args:
        RUBY_VERSION: '3.3.6'
    environment:
      - RAILS_ENV=development
      - BUNDLE_WITHOUT=""  
      - DATABASE_URL=postgres://postgres:postgres@db:5432/iswo_academy_development
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    command: "rails server -p 3001 -b 0.0.0.0"

  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  bundle_cache:
